# STUDENT NAME: MALIK FARHAN ALI AWAN PIAIC145699, AIC, BATCH-9, QUARTER-2

# ASSIGNMENT FOR NUMPY #1

# 1.  Import the numpy package under the name np


In [1]:
import numpy as np

# 2.Create a null vector of size 10


In [83]:
arrnull=np.zeros((10))

In [84]:
arrnull

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
arrnull.shape

(10,)

# 3.Create a vector with values ranging from 10 to 49

In [15]:
v=np.arange(10,49)

In [16]:
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 4. Find the shape of previous array in question 3

In [21]:
np.shape(v)

(39,)

# 5. Print the type of the previous array in question 3

In [22]:
v.dtype

dtype('int32')

# 6. Print the numpy version and the configuration

In [27]:
import numpy as np

In [40]:
print(np.__version__)

1.18.1


In [41]:
pip list

Package                            Version            
---------------------------------- -------------------
alabaster                          0.7.12             
anaconda-client                    1.7.2              
anaconda-navigator                 1.9.12             
anaconda-project                   0.8.3              
argh                               0.26.2             
asn1crypto                         1.3.0              
astroid                            2.3.3              
astropy                            4.0                
atomicwrites                       1.3.0              
attrs                              19.3.0             
autopep8                           1.4.4              
Babel                              2.8.0              
backcall                           0.1.0              
backports.functools-lru-cache      1.6.1              
backports.shutil-get-terminal-size 1.0.0              
backports.tempfile                 1.0                
backports.

In [43]:
np.version

<module 'numpy.version' from 'C:\\Users\\Owner\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

# 7.Print the dimension of the array in question 3

In [44]:
v.ndim

1

# 8.Create a boolean array with all the True values

In [45]:
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [47]:
arrt=v>9

In [48]:
arrt

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

# 9.Create a two dimensional array

In [52]:
arr2d=np.array([[1.,2.,3.],[4.,5.,6.]])

In [53]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
x=np.random.randn(10,2)

In [56]:
x

array([[ 2.5699706 ,  0.06732937],
       [-1.69492261,  0.42350927],
       [-0.47710635, -0.9355002 ],
       [-0.23503058,  0.19094189],
       [ 0.02593246, -0.21466127],
       [-0.89814864, -0.97246713],
       [-0.30273525, -1.65767362],
       [-2.2027643 , -1.18932784],
       [-0.65552007,  0.7916119 ],
       [ 0.80296764, -1.29413082]])

# 10. Create a three dimensional array

In [59]:
a=np.zeros((3,3,4))

In [60]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# 11.Reverse a vector (first element becomes last)

In [73]:
import numpy as np

In [74]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11])

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
f=np.flip(arr)

In [77]:
f

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 12. Create a null vector of size 10 but the fifth value which is 1

In [86]:
import numpy as np

In [119]:
vnull=np.zeros(10)

In [120]:
vnull

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
vnull.shape

(10,)

In [124]:
vnull[4]=1

In [126]:
vnull

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 13.Create a 3x3 identity matrix

In [127]:
x=np.ones((3,3))

In [128]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 14. arr = np.array([1, 2, 3, 4, 5])
Convert the data type of the given array from int to float

In [129]:
import numpy as np

In [130]:
arr=np.array([1,2,3,4,5])

In [131]:
arr

array([1, 2, 3, 4, 5])

In [132]:
arr.dtype

dtype('int32')

In [133]:
arr=arr.astype('float64')

In [134]:
arr.dtype

dtype('float64')

# 15.arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
Multiply arr1 with arr2

In [137]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])

In [138]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [139]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])

In [140]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [141]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

# 16. arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Make an array by comparing both the arrays provided above

In [142]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])

In [143]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [144]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])

In [145]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [146]:
compare=arr1==arr2

In [148]:
compare

array([[False, False, False],
       [False, False, False]])

# 17. Extract all odd numbers from arr with values(0-9)

In [149]:
import numpy as np

In [150]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [162]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
odd=np.where(arr%2)

In [168]:
odd

(array([1, 3, 5, 7, 9], dtype=int64),)

# 18.Replace all odd numbers to -1 from previous array

In [169]:
import numpy as np

In [170]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [171]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [216]:

np.where(arr%2,-1,arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 19. arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [217]:
arr=np.arange(10)

In [218]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
arr[5:9]=12

In [226]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

# 20. Create a 2d array with 1 on the border and 0 inside

In [227]:
x=np.ones((5,5))

In [228]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [229]:
x[1:-1,1:-1]=0

In [230]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 21. arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [232]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [233]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [235]:
arr2d[1:-1,1:-1]=12

In [236]:
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

# 22.arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [265]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [266]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [267]:
arr3d[0]=64

In [268]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# 23.Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [269]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [270]:
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [271]:
arr1d=arr2d[0]

In [272]:
arr1d

array([0, 1, 2, 3, 4])

# 24.Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [273]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [274]:
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [277]:
arr2d[1][1]

6

# 25.Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [278]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [279]:
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [331]:
arr2d[:2,2:3]

array([[2],
       [7]])

# 26.Create a 10x10 array with random values and find the minimum and maximum values

In [332]:
import numpy as np

In [334]:
arr=np.random.randn(10,10)

In [335]:
arr

array([[-0.94863162,  0.81712442, -0.48562876,  0.84778927, -0.62252821,
        -0.93744332,  0.63082564, -0.25970536,  0.21241413, -1.7175318 ],
       [ 1.39354345, -0.72836575, -0.71023   , -0.84737941,  0.69367134,
        -1.53015094,  0.25960478,  0.13380105,  0.10524114, -0.72618412],
       [-0.78995811, -0.44557908,  0.85068781, -1.0908512 , -0.80487647,
        -0.67493269, -0.12185598,  0.00858417, -0.17097441, -0.09990979],
       [ 0.35726556, -0.62167028, -0.47171087, -0.90815284, -0.10550608,
        -0.74729707,  1.31121624, -0.9239248 ,  0.45165184,  1.50772949],
       [ 0.79072832, -0.6258535 , -1.11691067, -0.62541284, -0.2434903 ,
        -0.79205777,  0.22887863, -1.21357241,  0.29389275,  0.61145443],
       [-1.8376708 , -0.35206659, -1.67769909,  0.46064638, -1.8043085 ,
        -0.43753064,  1.46129256,  2.44028859,  1.90667481, -0.54760572],
       [-0.08478045,  1.09389238, -1.19798041, -0.0134799 , -0.29331654,
        -0.57166845,  1.90925599, -1.42407358

In [337]:
np.max(arr)

2.4402885869100244

In [338]:
np.min(arr)

-1.8376707988758172

# 27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [339]:
a=np.array([1,2,3,2,3,4,3,4,5,6])

In [340]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [341]:
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [342]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [351]:
np.intersect1d(a,b)

array([2, 4])

# 28. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the positions where elements of a and b match

In [352]:
a=np.array([1,2,3,2,3,4,3,4,5,6])

In [353]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [354]:
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [356]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [357]:
c=np.where(a==b,"OK","NOT OK")

In [358]:
c

array(['NOT OK', 'OK', 'NOT OK', 'OK', 'NOT OK', 'OK', 'NOT OK', 'OK',
       'NOT OK', 'NOT OK'], dtype='<U6')

# 29. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [359]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [360]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [361]:
data=np.random.randn(7,4)

In [364]:
data

array([[ 0.55257575, -1.73772791,  0.12183261, -1.37024196],
       [ 1.51712704, -0.03592784,  0.45701633, -2.22656864],
       [ 0.15224373, -0.19187007,  1.52164447, -1.38030176],
       [-1.46844704, -1.9280207 ,  0.235563  , -0.37821783],
       [ 0.27002813, -0.65869362, -1.46065757, -0.75111926],
       [ 0.14132533,  0.73160872, -0.63708964, -1.1480761 ],
       [ 0.96501113, -0.67551784,  0.97426838,  0.49384286]])

In [375]:
data[names!='Will']

array([[ 0.55257575, -1.73772791,  0.12183261, -1.37024196],
       [ 1.51712704, -0.03592784,  0.45701633, -2.22656864],
       [-1.46844704, -1.9280207 ,  0.235563  , -0.37821783],
       [ 0.14132533,  0.73160872, -0.63708964, -1.1480761 ],
       [ 0.96501113, -0.67551784,  0.97426838,  0.49384286]])

# 30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will and Joe

In [402]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [403]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [404]:
data=np.random.randn(7,4)

In [405]:
data

array([[ 0.27668746, -1.70516452,  0.32007356, -0.13143298],
       [-1.06503196,  0.63326562, -0.23906918, -2.491662  ],
       [ 0.06370664,  0.15582441,  2.26376043, -1.54149264],
       [ 0.40656154,  0.36179316,  0.99204782,  0.05187662],
       [-0.50752729, -0.16446671, -0.56250064, -0.28481031],
       [-0.31697625, -1.44652843,  0.47465705,  0.16154054],
       [ 0.71377912, -0.11070352, -0.33321512, -1.34717827]])

In [406]:
mask=(names!='Will')|(names!="Joe")

In [407]:
mask

array([ True,  True,  True,  True,  True,  True,  True])

In [408]:
data[mask]

array([[ 0.27668746, -1.70516452,  0.32007356, -0.13143298],
       [-1.06503196,  0.63326562, -0.23906918, -2.491662  ],
       [ 0.06370664,  0.15582441,  2.26376043, -1.54149264],
       [ 0.40656154,  0.36179316,  0.99204782,  0.05187662],
       [-0.50752729, -0.16446671, -0.56250064, -0.28481031],
       [-0.31697625, -1.44652843,  0.47465705,  0.16154054],
       [ 0.71377912, -0.11070352, -0.33321512, -1.34717827]])

In [410]:
mask.dtype

dtype('bool')

# 31.Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [417]:
arr2d=np.arange(1,16)

In [418]:
arr2d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [419]:
arr2d.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [420]:
arr2d.dtype

dtype('int32')

In [421]:
arr2d=arr2d.astype('float64')

In [422]:
arr2d.dtype

dtype('float64')

In [423]:
arr2d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [424]:
arr2d.reshape(5,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

# 32.Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [425]:
arr3d=np.arange(1,17)

In [441]:
arr3d=arr3d.astype('float64')

In [442]:
arr3d.reshape(2,2,4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

# 33.Swap axes of the array you created in Question 32

In [443]:
arr3d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [444]:
arr3d.reshape(2,2,4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [445]:
np.vstack(arr3d)

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.]])

In [446]:
np.hstack(arr3d)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

# 34.Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [481]:
arr=np.arange(0.1,10)

In [482]:
arr

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1])

In [483]:
arrsqrt=np.sqrt(arr)

In [484]:
arrsqrt

array([0.31622777, 1.04880885, 1.44913767, 1.76068169, 2.02484567,
       2.25831796, 2.46981781, 2.66458252, 2.84604989, 3.01662063])

In [485]:
arrsqrt=np.where(arrsqrt<0.5,0,arrsqrt)

In [486]:
arrsqrt

array([0.        , 1.04880885, 1.44913767, 1.76068169, 2.02484567,
       2.25831796, 2.46981781, 2.66458252, 2.84604989, 3.01662063])

# 35.Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [492]:
arr1=np.random.randn(1,12)

In [493]:
arr1

array([[ 1.72109955, -1.13474856, -1.36328761, -0.92891814,  0.33628929,
         0.21817592, -1.60776516, -0.56759593,  0.26119622, -0.99175606,
         0.12807616, -0.5042704 ]])

In [494]:
arr2=np.random.randn(1,12)

In [495]:
arr2

array([[-0.19637288,  0.85902068,  1.24084308,  1.43588235, -0.15313328,
        -0.48978345,  1.96691202,  1.4443    , -1.78749214,  0.92808829,
         2.19588033,  0.29482999]])

In [497]:
arrmax=np.maximum(arr1,arr2)

In [498]:
arrmax

array([[1.72109955, 0.85902068, 1.24084308, 1.43588235, 0.33628929,
        0.21817592, 1.96691202, 1.4443    , 0.26119622, 0.92808829,
        2.19588033, 0.29482999]])

# 36.names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [500]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [501]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [502]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [503]:
np.sort(names)

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

# 37.a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [504]:
a=np.array([1,2,3,4,5])

In [505]:
a

array([1, 2, 3, 4, 5])

In [506]:
b=np.array([5,6,7,8,9])

In [513]:
np.delete(a,4)

array([1, 2, 3, 4])

# 38.Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [566]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [569]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [570]:
sampleArr=np.delete(sampleArray,1,1)

In [589]:
sampleArr

array([[34, 73],
       [82, 12],
       [53, 66]])

In [601]:
newColumn = np.array([[10,10,10]])

In [606]:
result = np.vstack((sampleArray, newColumn))

In [604]:
result

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66],
       [10, 10, 10]])

In [607]:
result

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66],
       [10, 10, 10]])

# 39. 
x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [608]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 

In [609]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [610]:
 y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [611]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [612]:
z=x.dot(y)

In [613]:
z

array([[ 28.,  64.],
       [ 67., 181.]])

# 40. Generate a matrix of 20 random values and find its cumulative sum

In [614]:
x=np.arange(0,20)

In [615]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [617]:
x.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)